### ISSUE TITLE
Missing model.h5 file

### ISSUE THREAD

**Issue by devanshkaushik** [adityaraj-mishra/PlantVillage-model#1]
https://github.com/adityaraj-mishra/PlantVillage-model/blob/9735a51756444b356e98bf6892058f18c6ce82e1/Program/model.py#L17

The `/content/model.h5` file is missing for the model.py file on line 17. Its the same case with the jupyter notebook file as well.

**Comment by adityaraj-mishra** [comment]
Will try to resolve the issue. It may work on ipynb file.

**Comment by adityaraj-mishra** [comment]
> https://github.com/adityaraj-mishra/PlantVillage-model/blob/9735a51756444b356e98bf6892058f18c6ce82e1/Program/model.py#L17
> 
> The `/content/model.h5` file is missing for the model.py file on line 17. Its the same case with the jupyter notebook file as well.

Steps to properly run the model:
1.  Create a new notebook in Google Colab. Copy the ipynb file code to that notebook and run it.
2.  After compiling and running the ipynb in google colab, it will generate the model.h5 file which you need to download.
3.  Keep the model.h5 file in the same directory as the .py file, run the .py file, and give the image as an input to validate the model.
